### ISSUE TITLE
Summarization example raises "Total length of `Dataloader` across ranks is zero" when on >1 GPUs 

### ISSUE THREAD

**Issue by soldni** [PyTorchLightning/lightning-flash#1153]
## 🐛 Bug

Hello! I am a new user of Lightning Flash and I am trying to run the [summarization example](https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/summarization.py) to familiarize myself with the framework. The code runs just fine on one GPU (set via `CUDA_VISIBLE_DEVICES`), but fails with 2 GPUs: 

```
Traceback (most recent call last):
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 208, in _wrapped_function
    result = function(*args, **kwargs)
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 236, in new_process
    results = trainer.run_stage()
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1285, in run_stage
    return self._run_train()
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/flash/core/trainer.py", line 98, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1367, in _run_sanity_check
    self._evaluation_loop._reload_evaluation_dataloaders()
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 170, in _reload_evaluation_dataloaders
    self.trainer.reset_val_dataloader()
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py", line 526, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py", line 483, in _reset_eval_dataloader
    if has_len_all_ranks(dataloader, self.training_type_plugin, module)
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 118, in has_len_all_ranks
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: Total length of `Dataloader` across ranks is zero. Please make sure that it returns at least 1 batch.
```

I am running PyTorch Lightning 1.5.5, Lightning Flash 0.6, and Pytorch 1.10.2 on CUDA 10.2. I also tried running the script on a machine with CUDA 11.3 with the same result. 

### To Reproduce

Install the following dependencies:

```
pytorch-lightning==1.5.5
lightning-flash[text]==0.6.0
torchmetrics==0.6.2
```

Run the following code:

```python 
from flash import Trainer
from flash.core.data.utils import download_data
from flash.text import SummarizationData, SummarizationTask


def main():
    # 1. Create the DataModule
    download_data("https://pl-flash-data.s3.amazonaws.com/xsum.zip", "./data/")

    datamodule = SummarizationData.from_csv(
        "input",
        "target",
        train_file="data/xsum/train.csv",
        val_file="data/xsum/valid.csv",
        batch_size=4,
    )

    # 2. Build the task
    model = SummarizationTask()

    # 3. Create the trainer and finetune the model
    trainer = Trainer(max_epochs=3, accelerator='auto', devices='auto')
    trainer.finetune(model, datamodule=datamodule)


if __name__ == '__main__':
    main()
```

### Expected behavior

Not to fail training.

### Environment

 - PyTorch Version (e.g., 1.0): 1.10.2
 - OS (e.g., Linux): Ubuntu 18.04.4
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Build command you used (if compiling from source): `N/A`
 - Python version: 3.9.7
 - CUDA/cuDNN version: 10.2 (also tried on 11.3)
 - GPU models and configuration: Quadro RTX 8000 (also tried on V100 on `p3.8xlarge` AWS instance)

**Comment by soldni** [comment]
Update: even when not providing the validation dataloader, i.e. when running 
```python
trainer.finetune(model, train_dataloader=datamodule.train_dataloader())
```
the error persists:
```
Traceback (most recent call last):
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 208, in _wrapped_function
    result = function(*args, **kwargs)
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 236, in new_process
    results = trainer.run_stage()
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1285, in run_stage
    return self._run_train()
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/flash/core/trainer.py", line 108, in _run_train
    self.reset_train_val_dataloaders(model)
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py", line 567, in reset_train_val_dataloaders
    self.reset_train_dataloader(model=model)
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py", line 366, in reset_train_dataloader
    self.train_dataloader = CombinedLoader(self.train_dataloader, self._data_connector.multiple_trainloader_mode)
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/supporters.py", line 351, in __init__
    self._wrap_loaders_max_size_cycle()
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/supporters.py", line 447, in _wrap_loaders_max_size_cycle
    all_lengths = apply_to_collection(self.loaders, Iterable, get_len, wrong_dtype=(Sequence, Mapping))
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/utilities/apply_func.py", line 92, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 156, in get_len
    if has_len(dataloader):
  File "/home/lucas/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 84, in has_len
    raise ValueError("`Dataloader` returned 0 length. Please make sure that it returns at least 1 batch")
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch
```

**Comment by Borda** [comment]
@ethanwharris I guess this is the same issue I was facing last week with running multi-GPU training...
