### ISSUE TITLE
Flash doesn't support albumentations transforms

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#161]
## 🐛 Bug

You have to pass data to augmentations as named arguments, for example: aug(image=image). Flash doesn't provide functionality for this with the existing data pipeline.

### To Reproduce

```python
train_transform = albumentations.Compose(
            [
                albumentations.RandomResizedCrop(height=image_size, width=image_size, scale=(0.9, 1), p=1),
                albumentations.HorizontalFlip(p=0.5),
                albumentations.ShiftScaleRotate(p=0.5)
            ]
)

data = ImageClassificationData.from_filepaths(
    train_transform = train_transform,
    batch_size=32,
    train_filepaths=os.path.join(root, 'train'),
    train_labels=train_labels,
    valid_split=0.10,
    num_workers=4
)


```

KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 272, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/opt/conda/lib/python3.7/site-packages/flash/vision/classification/data.py", line 77, in __getitem__
    img = self.transform(img)
  File "/opt/conda/lib/python3.7/site-packages/albumentations/core/composition.py", line 165, in __call__
    raise KeyError("You have to pass data to augmentations as named arguments, for example: aug(image=image)")
KeyError: 'You have to pass data to augmentations as named arguments, for example: aug(image=image)'

**Comment by aribornstein** [comment]
I have a prototype fix but it is out of sync with master
https://github.com/aribornstein/lightning-flash/tree/flash_multilabel_clf_aug

**Comment by edgarriba** [comment]
@aribornstein could you try again ? I believe this can now achieved

**Comment by hzitoun** [comment]
Having the same issue!

**Comment by aribornstein** [comment]
@edgarriba I think this is still broken.
