### ISSUE TITLE
SemanticSegmentationData.from_folders() - Dataloader issue - stack expects each tensor to be equal size, but got [3, 200, 200] at entry 0 and [1, 200, 200] at entry 13

### ISSUE THREAD

**Issue by kurtjcu** [PyTorchLightning/lightning-flash#415]
## 🐛 Bug
SemanticSegmentationData.from_folders() has an issue in the dataloader where incorrect sized tensors can be retrieved.

### To Reproduce

1. use a version of the coco dataset where the masks  have been processed to .jpg using coco2voc.
2. Load the dataset using  SemanticSegmentationData.from_folders()
3. get batches from the dataloader

##### Note* All images have been checked to see if they contain the correct dimensions using
'''
import torch
from torch

#### error message
'''
Epoch 0:   0%|          | 1/7639 [00:02<5:01:55,  2.37s/it]
Epoch 0:   0%|          | 1/7639 [00:02<5:02:01,  2.37s/it, loss=5.67, v_num=4, val_iou=1.45e-5, val_cross_entropy=24.60]
Epoch 0:   0%|          | 2/7639 [00:03<3:51:22,  1.82s/it, loss=5.67, v_num=4, val_iou=1.45e-5, val_cross_entropy=24.60]
Epoch 0:   0%|          | 2/7639 [00:03<3:51:25,  1.82s/it, loss=5.65, v_num=4, val_iou=1.45e-5, val_cross_entropy=24.60, train_iou_step=7.35e-5, train_cross_entropy_step=5.670]Traceback (most recent call last):
  File "train_flash_example.py", line 67, in <module>
    trainer.finetune(model, datamodule=datamodule, strategy="freeze")
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/flash/core/trainer.py", line 148, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 869, in run_train
    self.train_loop.run_training_epoch()
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    for batch_idx, (batch, is_last_batch) in train_dataloader:
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/profiler/profilers.py", line 112, in profile_iterable
    value = next(iterator)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 534, in prefetch_iterator
    for val in it:
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 464, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 478, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 85, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
    return self._process_data(data)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/flash/core/data/batch.py", line 177, in forward
    samples = self.collate_fn(samples)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/flash/core/data/utils.py", line 185, in forward
    return self.func(*args, **kwargs)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/flash/core/data/process.py", line 367, in collate
    return self.current_transform(samples)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/flash/core/data/utils.py", line 185, in forward
    return self.func(*args, **kwargs)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/flash/core/data/transforms.py", line 108, in kornia_collate
    return default_collate(samples)
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 200, 200] at entry 0 and [1, 200, 200] at entry 13

Exception ignored in: <function tqdm.__del__ at 0x7f25f1dcb670>
Traceback (most recent call last):
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/tqdm/std.py", line 1299, in close
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/tqdm/std.py", line 1492, in display
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __str__
  File "/home/kurt/anaconda3/envs/flash_coco/lib/python3.8/site-packages/tqdm/std.py", line 1450, in format_dict
TypeError: cannot unpack non-iterable NoneType object
'''

#### Code sample (condensed for this post)
'''
from flash.image import SemanticSegmentationData

datamodule = SemanticSegmentationData.from_folders(
    train_folder="/data2/Datasets/coco/images/train2017",
    train_target_folder="/data2/Datasets/coco/annotations/instances_train2017/class_labels", 
    val_folder="/data2/Datasets/coco/images/val2017",
    val_target_folder="/data2/Datasets/coco/annotations/instances_val2017/class_labels",
    batch_size=8,
    # val_split=0.3,
    image_size=(200, 200),  # (600, 800)
    num_classes=255,
)

# print(datamodule.train_dataloader)

train_dataloader = datamodule.train_dataloader()

for batch in iter(train_dataloader):
# batch = next(iter(train_dataloader))
# print(batch)
    if len(batch["input"][0]) != 3:
        print(len(batch["input"][0]))
        print(batch["target"][0])
        print(batch["metadata"])
'''

### Expected behavior

Dataloader should return images in their original dimensions. 

### Environment

'''
name: flash_coco
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _pytorch_select=0.1=cpu_0
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py38h497a2fe_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.5.30=ha878542_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.5=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - click=8.0.1=py38h578d9bd_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cudatoolkit=11.1.1=h6406543_8
  - dataclasses=0.8=pyhc8e2a94_1
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py38h578d9bd_3
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth=1.30.0=pyh44b312d_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.38.0=py38hdd6454d_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.5.0=py38h578d9bd_0
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libgomp=9.3.0=h2828fa1_19
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libmklml=2019.0.5=0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.17.2=h780b84a_0
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.41.0=h7f98852_0
  - libwebp-base=1.2.0=h7f98852_2
  - lz4-c=1.9.3=h9c3ff4c_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - mkl=2020.2=256
  - multidict=5.1.0=py38h497a2fe_1
  - ncurses=6.2=h58526e2_4
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.20.3=py38h9894fe3_1
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pillow=8.2.0=py38he98fc37_0
  - pip=21.1.2=pyhd8ed1ab_0
  - protobuf=3.17.2=py38h709712a_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydeprecate=0.3.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.10=h49503c6_1_cpython
  - python_abi=3.8=1_cp38
  - pytorch=1.8.1=py3.8_cuda11.1_cudnn8.0.5_0
  - pytorch-lightning=1.3.5=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_0
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - setuptools=49.6.0=py38h578d9bd_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.35.5=h74cdb3f_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tk=8.6.10=h21135ba_1
  - torchmetrics=0.3.2=pyhd8ed1ab_0
  - torchvision=0.9.1=py38_cu111
  - tqdm=4.61.1=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h497a2fe_1
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - cycler==0.10.0
    - cython==0.29.23
    - fsspec==2021.5.0
    - kiwisolver==1.3.1
    - kornia==0.5.4
    - lightning-bolts==0.3.3
    - lightning-flash==0.3.2
    - matplotlib==3.4.2
    - pandas==1.2.4
    - pycocotools==2.0.2
    - python-dateutil==2.8.1
    - pytz==2021.1
    - timm==0.4.9
prefix: /home/kurt/anaconda3/envs/flash_coco
'''

### Additional context

vision import transforms
from PIL import Image
import glob

# loader uses the transforms function that comes with torchvision
loader = transforms.Compose([
    transforms.ToTensor()])  

unloader = transforms.ToPILImage()

img_dir = "/data2/Datasets/coco/images/train2017/*.jpg"
# img_dir = "/data2/Datasets/coco/annotations/instances_val2017/class_labels/*.jpg"

def image_loader(image_name):
    image = Image.open(image_name).convert('RGB')
    image = loader(image).unsqueeze(0)
    return image

idx = 0
for img in glob.glob(img_dir):
    size = image_loader(img).size()
    # print(size[1], img)
    if size [1] != 3:
        print(size[1], img)

    idx = idx + 1
    # if idx >= 10:
    #     quit()

print("total images ", idx)
'''

**Comment by edgarriba** [comment]
@kurtjcu this problem seems more related to the data, not to flash itself.

To debug your problem I would suggest first to catch the image path that raises your error and verify visually that the image is not corrupted.

**Comment by kurtjcu** [comment]
Your correct, my checking code converted the greyscale images to RGB, sorry for wasting your time. :)
