### ISSUE TITLE
TypeError: __array__() takes 1 positional argument but 2 were given encountered during trainer.finetune

### ISSUE THREAD

**Issue by plaban1981** [PyTorchLightning/lightning-flash#500]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
TypeError: __array__() takes 1 positional argument but 2 were given encountered during trainer.finetune operation
#### Code

# 2. Load the data
datamodule = ImageClassificationData.from_folders(
    train_folder="/content/drive/MyDrive/dphi/Kvasir/The Kvasir-Capsule/TRAIN/",
    val_folder="/content/drive/MyDrive/dphi/Kvasir/The Kvasir-Capsule/VAL/",
    predict_folder="/content/drive/MyDrive/dphi/Kvasir/The Kvasir-Capsule/test/",
)

# 3 Build the model
model = ImageClassifier(backbone="densenet121", num_classes=datamodule.num_classes)

# 4. Train the model
trainer.finetune(model, datamodule=datamodule, strategy=FreezeUnfreeze(unfreeze_epoch=1))

Error encountered :-
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flash/core/data/batch.py", line 223, in forward
    sample = self.per_sample_transform(sample)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flash/core/data/batch.py", line 76, in forward
    sample = self.to_tensor_transform(sample)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flash/core/data/utils.py", line 185, in forward
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flash/core/data/process.py", line 354, in to_tensor_transform
    return self.current_transform(sample)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flash/core/data/transforms.py", line 45, in forward
    outputs = super().forward(inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flash/core/data/utils.py", line 185, in forward
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 97, in __call__
    return F.to_tensor(pic)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py", line 129, in to_tensor
    np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
TypeError: __array__() takes 1 positional argument but 2 were given

#### What's your environment?
Lightning-flash version :0.4.1dev
Lightning version : 1.3.8
Coding in Google Colab
 - OS: [e.g. iOS, Linux, Win]
 - Packaging [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by ethanwharris** [comment]
Hi @plaban1981 Thanks for the question. I think this is a torchvision / pillow issue. Could you try some of the solutions here: https://github.com/pytorch/pytorch/issues/61125#issuecomment-872624273

**Comment by plaban1981** [comment]
Hi @ethanwharris ,
Requirement already satisfied: pillow==8.2.0 in /usr/local/lib/python3.7/dist-packages (8.2.0)
Already have pilow version 8.2.0, Encounter the issue still

**Comment by ethanwharris** [comment]
Hi @plaban1981, could you try downgrading pytorch / torchvision as described here instead? https://github.com/pytorch/pytorch/issues/61125#issuecomment-872359243

**Comment by plaban1981** [comment]
Hi @ethanwharris 

Requirement already satisfied: torch==1.9 in /usr/local/lib/python3.7/dist-packages (1.9.0+cu102)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch==1.9) (3.7.4.3)

The required vesrion is present already

**Comment by ethanwharris** [comment]
Hi @plaban1981, that comment says to downgrade to torch==1.8.1 torchvision==0.9.1, could you try that instead?

**Comment by plaban1981** [comment]
Hi @ethanwharris 

doing a  sudo pip install pillow==8.2.0 instead of pip install worked!!
I no longer encounter the type error.
Thanks for all the help extended.

**Comment by ethanwharris** [comment]
Hi @plaban1981 great! Glad you got it working :smiley:
