### ISSUE TITLE
Using "slowfast_r50" in video classification example

### ISSUE THREAD

**Issue by TimoMartens** [PyTorchLightning/lightning-flash#631]
## 🐛 Bug
I've been trying to use lightning-flash to finetune a slowfast model on my custom data. However, when I follow the example with "slowfast_r50" instead of "x3d_xs" on https://lightning-flash.readthedocs.io/en/latest/reference/video_classification.html I get the following error: AssertionError: input for MultiPathWayWithFuse needs to be a list of tensors.
I assume that this is because slowfast requires the slow and fast path of a video as input, but VideoClassificationData.from_folders() doesn't provide this. How can I solve this?

### To Reproduce

1. Go to https://lightning-flash.readthedocs.io/en/latest/reference/video_classification.html
2. Run the provided code example for video classification but instead of using the "x3d_xs" backbone, use "slowfast_r50" as backbone.
3. Scroll down to code sample for reproducability

### Stack trace

```
Validation sanity check:   0%|                                                                   | 0/2 [00:00<?, ?it/s]Uncaught exception
Traceback (most recent call last):
  File "trainer.py", line 34, in <module>
    trainer.finetune(model, datamodule=datamodule, strategy="freeze")
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\flash\core\trainer.py", line 157, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 553, in fit
    self._run(model)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 918, in _run
    self._dispatch()
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 996, in run_stage
    return self._run_train()
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1031, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1115, in _run_sanity_check
    self._evaluation_loop.run()
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 111, in advance
    dataloader_iter, self.current_dataloader_idx, dl_max_batches, self.num_dataloaders
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 110, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 154, in evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 211, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 178, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\flash\core\model.py", line 201, in validation_step
    output = self.step(batch, batch_idx)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\flash\video\classification\model.py", line 149, in step
    return super().step((batch["video"], batch["label"]), batch_idx)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\flash\core\model.py", line 165, in step
    y_hat = self(x)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\flash\video\classification\model.py", line 152, in forward
    x = self.backbone(x)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorchvideo\models\net.py", line 43, in forward
    x = self.blocks[idx](x)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\timom\anaconda3\envs\tennis\lib\site-packages\pytorchvideo\models\net.py", line 80, in forward
    ), "input for MultiPathWayWithFuse needs to be a list of tensors"
AssertionError: input for MultiPathWayWithFuse needs to be a list of tensors
```

#### Code sample

```py
import os
from pytorch_lightning import seed_everything

import flash
from flash.core.classification import Labels
from flash.core.data.utils import download_data
from flash.video import VideoClassificationData, VideoClassifier

seed_everything(42)

datamodule = VideoClassificationData.from_folders(
    train_folder=os.path.join(os.getcwd(), "data/Train/"),
    val_folder=os.path.join(os.getcwd(), "data/Val/"),
    clip_sampler="uniform",
    clip_duration=1,
    decode_audio=False,
    batch_size=4,
)

model = VideoClassifier(backbone="slowfast_r50", num_classes=datamodule.num_classes, pretrained=True)

trainer = flash.Trainer(max_epochs=10, gpus=1, auto_scale_batch_size=True, auto_lr_find=True)

trainer.finetune(model, datamodule=datamodule, strategy="freeze")

trainer.save_checkpoint("video_classification_model.pt")
```

### Expected behavior
I expect the model to start finetuning without any errors, just as what would happen if you use the "x3d_xs" backbone.

### Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - Pytorch-lightning Version: 1.4.0
 - Pytorchvideo Version: 0.1.0
 - OS (e.g., Linux): Windows 10 professional
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7.10
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: GTX 1050

### Additional context

My thoughts on this:
I assume it has something to do with the fact that a slowfast model expects both a slow and fast path as input. `VideoClassificationData.from_folders()` seems to only provide the fast path to the model, which results in this error.

**Comment by wolfworld6** [comment]
hi, did you solve it?
