### ISSUE TITLE
custom transforms not applied correctly

### ISSUE THREAD

**Issue by ananyahjha93** [PyTorchLightning/lightning-flash#689]
## 🐛 Bug

TypeError when passing in custom transform via Preprocess object.

### To Reproduce

Steps to reproduce the behaviour:

```py
import torchvision.transforms as T
from flash.core.data.process import DefaultPreprocess
from flash.image import ImageClassificationData
from torchvision.datasets import CIFAR10

preprocess = DefaultPreprocess(train_transform={'pre_tensor_transform': T.RandomHorizontalFlip()})

datamodule = ImageClassificationData.from_datasets(
    train_dataset=CIFAR10('.', download=True),
    preprocess=preprocess,
)

train_dataloader = datamodule._train_dataloader()

for batch in train_dataloader:
    x = batch[DefaultDataKeys.INPUT]
    print(x.shape)
```

```
Traceback (most recent call last):
  File "/Users/ananya/lightning/lightning-flash/flash_examples/local_example.py", line 31, in <module>
    for batch in train_dataloader:
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/ananya/lightning/lightning-flash/flash/core/data/batch.py", line 221, in forward
    sample = self.per_sample_transform(sample)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/ananya/lightning/lightning-flash/flash/core/data/batch.py", line 71, in forward
    sample = self.pre_tensor_transform(sample)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/ananya/lightning/lightning-flash/flash/core/data/utils.py", line 178, in forward
    return self.func(*args, **kwargs)
  File "/Users/ananya/lightning/lightning-flash/flash/core/data/process.py", line 341, in pre_tensor_transform
    return self.current_transform(sample)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 627, in forward
    return F.hflip(img)
  File "/usr/local/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 536, in hflip
    return F_pil.hflip(img)
  File "/usr/local/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py", line 39, in hflip
    raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
TypeError: img should be PIL Image. Got <class 'dict'>
```

### Expected behavior

In flash/core/data/process.py, when self.current_transform is identity, it correctly works on a sample of dict class where the image is put against the key DefaultDataKeys.INPUT. But when the user passes a custom transform or composition of transforms, the process.py file calls the transform on the dict object directly and fails.

```
    def pre_tensor_transform(self, sample: Any) -> Any:
        """Transforms to apply on a single object."""
        return self.current_transform(sample)
```

### Environment

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ethanwharris** [comment]
Hi @ananyahjha93, you should use ApplyToKeys for this to work correctly. There's an example usage here: https://lightning-flash.readthedocs.io/en/latest/reference/image_classification.html#custom-transformations

There was some suggestion that we could just automatically apply to the inuput key if no apply to keys is used, there's an issue open for that here #645 

Hope that helps :smiley:
