### ISSUE TITLE
Highlight the correct combination of heads/backbone in Object Detection

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [PyTorchLightning/lightning-flash#829]
## 🐛 Bug

Currently, there is no way to know which head goes with which backbone in the ObjectDetection task

```python
model = ObjectDetector(
    head="mmdet_fcos", num_classes=datamodule.num_classes, image_size=128
)
```
I have `mmcv-full` installed

Most of the code has no types, so it is impossible to find where the hell the backbones are defined. 

Would it be possible to add from your side the correct list of which backbone can be used?

```
   raise KeyError(f"Key: {key} is not in {type(self).__name__}")
KeyError: 'Key: resnet18_fpn is not in FlashRegistry'
```

Thank you.

Cheers,

Francesco

**Comment by ethanwharris** [comment]
Hi @FrancescoSaverioZuppichini Thanks for the question. I think our documentation here is lacking, but you should be able to get the list with:
```
ObjectDetector.available_backbones("mmdet_fcos")
```

Hope that helps :smiley:

**Comment by FrancescoSaverioZuppichini** [comment]
hey @ethanwharris , thanks ;) I was printing them from the source code. So, after selecting one backbone

```
['resnet101_caffe_fpn_gn_head_1x_coco', 'resnet101_caffe_fpn_gn_head_mstrain_640_800_2x', 'resnet50_caffe_fpn_gn_head', 'resnet50_caffe_fpn_gn_head_center_normbbox_centeronreg_giou', 'resnet50_caffe_fpn_gn_head_dcn_1x_center_normbbox_centeronreg_giou', 'resnet50_caffe_fpn_gn_head_mstrain_640_800_2x', 'resnext101_64x4d_fpn_gn_head_mstrain_640_800_2x']
```

```python
model = ObjectDetector(
    head="mmdet_fcos",
    backbone="resnet50_caffe_fpn_gn_head_mstrain_640_800_2x",
    num_classes=datamodule.num_classes,
    image_size=128,
)
```

Obviously, an error:


```
Traceback (most recent call last):
  File "/home/zuppif/playground.py", line 26, in <module>
    model = ObjectDetector(
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/flash/image/detection/model.py", line 76, in __init__
    adapter = metadata["metadata"]["adapter"].from_task(
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/flash/image/detection/backbones.py", line 53, in from_task
    return super().from_task(
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/flash/core/utilities/url_error.py", line 24, in wrapper
    return fn(*args, pretrained=pretrained, **kwargs)
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/flash/core/integrations/icevision/adapter.py", line 77, in from_task
    model_type, model, icevision_adapter, backbone = metadata["fn"](
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/flash/core/registry.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/flash/core/integrations/icevision/backbones.py", line 47, in load_icevision_ignore_image_size
    return load_icevision(adapter, model_type, backbone, num_classes, **kwargs)
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/flash/core/integrations/icevision/backbones.py", line 36, in load_icevision
    model = model_type.model(backbone=backbone, num_classes=num_classes, **kwargs)
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/icevision/models/mmdet/common/bbox/single_stage/model.py", line 19, in model
    return build_model(
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/icevision/models/mmdet/common/utils.py", line 66, in build_model
    _model = build_detector(cfg.model, cfg.get("train_cfg"), cfg.get("test_cfg"))
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zuppif/miniconda3/lib/python3.9/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: FCOS: FPN: __init__() got an unexpected keyword argument 'extra_convs_on_inputs'
```

I got this very familiar configuration error from inside `mmcv`.  So what the hell is going on.

Flash uses `icevision` that has some magic to call `mmdet/mmcv` that has this error. So this seems to be useless. Have you guys test for using head/backbones from mmdet? I would like to see if they have failed recently, if not then probably my version is wrong. I am using the latest one for `mmcv` -> `1.3.14` and `flash` -> `0.5.0`

**Comment by FrancescoSaverioZuppichini** [comment]
btw `icevision` has a ton of issues making it virtually useless (one of them is the hardocded version of mmdet). I suggest to stay away from it or maybe you can help them out. I have wasted one day full of work trying to get the correct version of mmdet to work with it. The release is months old and till they fix all the issues I believe you should also **clearly state that object detection in flash doesn't work**

**Comment by FrancescoSaverioZuppichini** [comment]
Hey @ethanwharris , thank you for your reply. I would personally stay away from icevision since they depend on too many libraries but I am not use about an alternative
