### ISSUE TITLE
Finetune.py Wav2Vec2 KeyError with DeepSpeed Pluggin

### ISSUE THREAD

**Issue by choclatier** [PyTorchLightning/lightning-flash#862]
## 🐛 Bug

An error is thrown when trying to finetune model `facebook/wav2vec2-large-robust-ft-swbd-300h` using the DeepSpeedPlugin running any stage 1,2 or 3.

```
 File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/callbacks/finetuning.py", line 270, in <listcomp>
    group_state["params"] = [mapping[p] for p in g["params"]]
KeyError: tensor([ 0.9736,  0.8472, -0.4827,  ..., -0.0599, -0.0684, -0.0645],
       device='cuda:0', requires_grad=True)
```
### To Reproduce

```python
import torch
import flash
from flash.audio import SpeechRecognition, SpeechRecognitionData
import json
from pytorch_lightning  import loggers, plugins
from torch.utils.data.sampler import BatchSampler
# 0. Logger
logger = loggers.TensorBoardLogger('lightning_logs/')
# 1. Create the DataModule

datamodule = SpeechRecognitionData.from_json(
    input_fields="file",
    target_fields="text",
    train_file="data/train.json",
    test_file="data/test.json",
    val_file="data/val.json"
)
datamodule.num_workers = 6
datamodule.pin_memory = True

# 2. Build the task

model = SpeechRecognition(backbone="facebook/wav2vec2-large-robust-ft-swbd-300h")
model.hparams.learning_rate = 3e-05

# 3. Create the trainer and finetune the model
trainer = flash.Trainer(check_val_every_n_epoch=1,
                        max_epochs=1,
                        logger=logger, 
                        fast_dev_run=1,
                        num_processes=10,
                        log_every_n_steps=200,                   
                        plugins=plugins.DeepSpeedPlugin(stage=3),
                        gpus=torch.cuda.device_count(),
                        precision=16)
trainer.finetune(model, datamodule=datamodule, strategy="no_freeze")

# 4. Predict on audio files!
predictions = model.predict(["data/example.wav"])
print(predictions)

# 5. Save the model!
trainer.save_checkpoint("speech_recognition_model.pt")
```
### Error Traceback
```

Traceback (most recent call last):
  File "train.py", line 56, in <module>
    trainer.finetune(model, datamodule=datamodule, strategy="no_freeze")
  File "/home/.local/lib/python3.8/site-packages/flash/core/trainer.py", line 165, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 106, in run
    self.on_run_start(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 106, in on_run_start
    self.trainer.call_hook("on_train_epoch_start")
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1228, in call_hook
    trainer_hook(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 92, in on_train_epoch_start
    callback.on_train_epoch_start(self, self.lightning_module)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/callbacks/finetuning.py", line 298, in on_train_epoch_start
    self._store(pl_module, opt_idx, num_param_groups, current_param_groups)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/callbacks/finetuning.py", line 283, in _store
    self._internal_optimizer_metadata[opt_idx] = self.__apply_mapping_to_param_groups(
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/callbacks/finetuning.py", line 270, in __apply_mapping_to_param_groups
    group_state["params"] = [mapping[p] for p in g["params"]]
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/callbacks/finetuning.py", line 270, in <listcomp>
    group_state["params"] = [mapping[p] for p in g["params"]]
KeyError: tensor([ 0.9736,  0.8472, -0.4827,  ..., -0.0599, -0.0684, -0.0645],
       device='cuda:0', requires_grad=True)
```

### Expected behavior

It should start finetuning.

### Environment

 - PyTorch Version: 1.9.1
 - OS: Ubuntu Linux
 - How you installed PyTorch (`conda`, `pip`, source): `pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html`
 - Python version: 3.8.10
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: 4 x NVIDIA GEFORCE RTX 3070
 - Any other relevant information: Intel i9, 64GB of RAM

### Additional context

I can't seem to succefully utilize any sort of GPU parallelization to finetune this model and library. Its 351 million parameters but I would think I should be able to fine tune it some. If any one has any suggestions to finetune (I also tried DP, DPP, DPP2 all with OOM getting thrown) this model with my setup I would appreciate it. Its 24 GB of vRAM split onto 4 GPUS.

**Comment by SeanNaren** [comment]
Thanks @choclatier 

we've noticed that using finetune with DeepSpeed is leading to some issues: https://github.com/microsoft/DeepSpeed/issues/1426

A short term fix would be to use `trainer.fit` instead of `finetune`, and drop the learning rate. This does mean custom fine-tuning strategies are out the window for now (but from personal experience, in most cases you want to fine-tune the entire transformer network).
