### ISSUE TITLE
Image Classifier load from checkpoint in docs not running

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#864]
## 🐛 Bug

```
Traceback (most recent call last):
  File "grid_gradio_demo.py", line 8, in <module>
    model = ImageClassifier.load_from_checkpoint("https://flash-weights.s3.amazonaws.com/image_classification_model.pt")
  File "/home/jovyan/conda/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 131, in load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=lambda storage, loc: storage)
  File "/home/jovyan/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/cloud_io.py", line 30, in load
    return torch.hub.load_state_dict_from_url(str(path_or_url), map_location=map_location)
  File "/home/jovyan/conda/lib/python3.8/site-packages/torch/hub.py", line 557, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/jovyan/conda/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/jovyan/conda/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/jovyan/conda/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'identity_collate_fn' on <module 'flash.core.adapter' from '/home/jovyan/conda/lib/python3.8/site-packages/flash/core/adapter.py'>
```

Code to reproduce 

```python

import flash
from flash.core.data.utils import download_data
from flash.image import ImageClassifier

# 1. Download data
download_data("https://pl-flash-data.s3.amazonaws.com/hymenoptera_data.zip", "./data")
# 2. Load Model
model = ImageClassifier.load_from_checkpoint("https://flash-weights.s3.amazonaws.com/image_classification_model.pt")
# 3. Predict 
predictions = model.predict("data/hymenoptera_data/val/bees/65038344_52a45d090d.jpg")
print(predictions)

```

**Comment by aribornstein** [comment]
Note if I train my own model it will run we should update the example weights.

**Comment by dmarx** [comment]
Tried your code in colab, prepended with `!pip install lightning-flash[image] torchmetrics`. I'm getting back the classification `['ants']`, which is incorrect but not an error response like what you posted. Was the file updated? Try again, maybe you can close the issue.

**Comment by ethanwharris** [comment]
This should be working now. @aribornstein Note that you may need to clear your cache for it to work:
```
rm ~/.cache/torch/hub/checkpoints/*
```
