### ISSUE TITLE
Support passing file encoding / additional args for CSV / JSON files

### ISSUE THREAD

**Issue by BakingBrains** [PyTorchLightning/lightning-flash#987]
I am trying to finetuning wav2vec model for code switching. My json data file contains some characters from a different language (Hindi).
While loading I am getting this error. 

```
Using custom data configuration default-e6037235814b16b2
100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]
Failed to read file 'D:\pycharmprojects\wav2vec_finetuneing\train_data.json' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Invalid escape character in string. in row 2
Traceback (most recent call last):
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\datasets\packaged_modules\json\json.py", line 140, in _generate_tables
    dataset = json.load(f)
  File "C:\Users\syeda\AppData\Local\Programs\Python\Python37\Lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\syeda\AppData\Local\Programs\Python\Python37\Lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\syeda\AppData\Local\Programs\Python\Python37\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 4185)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/pycharmprojects/wav2vec_finetuneing/train.py", line 17, in <module>
    train_file=r"D:\pycharmprojects\wav2vec_finetuneing\train_data.json",
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\flash\core\data\data_module.py", line 1035, in from_json
    **input_transform_kwargs,
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\flash\core\data\data_module.py", line 589, in from_input
    predict_data,
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\flash\core\data\io\input.py", line 307, in to_datasets
    train_dataset = self.generate_dataset(train_data, RunningStage.TRAINING)
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\flash\core\data\io\input.py", line 342, in generate_dataset
    data = load_data(data, mock_dataset)
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\flash\audio\speech_recognition\data.py", line 95, in load_data
    dataset_dict = load_dataset(self.filetype, data_files={stage: str(file)})
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\datasets\load.py", line 1637, in load_dataset
    use_auth_token=use_auth_token,
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\datasets\builder.py", line 608, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\datasets\builder.py", line 697, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\datasets\builder.py", line 1157, in _prepare_split
    generator, unit=" tables", leave=False, disable=True  # bool(logging.get_verbosity() == logging.NOTSET)
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\tqdm\std.py", line 1168, in __iter__
    for obj in iterable:
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\datasets\packaged_modules\json\json.py", line 142, in _generate_tables
    raise e
  File "D:\pycharmprojects\wav2vec_finetuneing\venv\lib\site-packages\datasets\packaged_modules\json\json.py", line 119, in _generate_tables
    io.BytesIO(batch), read_options=paj.ReadOptions(block_size=block_size)
  File "pyarrow\_json.pyx", line 246, in pyarrow._json.read_json
  File "pyarrow\error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Invalid escape character in string. in row 2
```

Any suggestions?

Thanks

**Comment by ethanwharris** [comment]
Hi @BakingBrains thanks for reporting this. We had similar issues in our CSV loading where certain unicode characters would cause issues. I think we should be able to have a similar fix here, or could at least expose an encoding argument so that these files can be loaded. Would you mind sharing a snippet of your JSON data (or some more details about the file encoding) so that we can investigate further? Thanks :smiley:

**Comment by BakingBrains** [comment]
Thanks @ethanwharris 

Exposing an encoding argument would be more helpful.

Here is the snippet of the JSON file.
[https://drive.google.com/file/d/1YjUw-K8LtqeOked_R7PD67dta8V_rThu/view?usp=sharing](https://drive.google.com/file/d/1YjUw-K8LtqeOked_R7PD67dta8V_rThu/view?usp=sharing)
