### ISSUE TITLE
No module named 'flash.core'

### ISSUE THREAD

**Issue by valeriano-manassero** [PyTorchLightning/lightning-flash#991]
## 🐛 Bug

I'm not totally sure but I have issues while trying to use Flash package 0.5.2, I tried on many brand new condo environments.

### To Reproduce

1. Install latest version (0.5.2) with pip
2. open a Python console
3. do a `from flash.core.data.utils import download_data`
```
Python 3.7.11 (default, Jul 27 2021, 07:03:16) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from flash.core.data.utils import download_data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/valerianomanassero/GitHub/valeriano-manassero/clearml-pipelines/test-lightning/flash.py", line 3, in <module>
    from flash.core.data.utils import download_data
ModuleNotFoundError: No module named 'flash.core'; 'flash' is not a package
```

#### Code sample

A simple import is giving me issues.

### Environment

 - PyTorch Version (e.g., 1.0): 1.10
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): -
 - Python version: 3.7 and 3.8 (tried both)
 - CUDA/cuDNN version: -
 - GPU models and configuration: -
 - Any other relevant information: -

**Comment by ethanwharris** [comment]
Hi @valeriano-manassero thanks for reporting this. This looks like an installation issue, could you share the command you used to install Flash? Thanks :smiley:

**Comment by valeriano-manassero** [comment]
Thank you for helping me figure out the issue :) , in fact I discovered after posting this issue that my dev system was totally broken, after reinstalling Conda, recreating env from scratch, everything was good.

Sorry if I disturbed you with this, we can close it.

Thank you again.

**Comment by ethanwharris** [comment]
Hey @valeriano-manassero No disturbance at all, glad you were able to get it working! :smiley:
